name: Manual deploy

on:
  workflow_dispatch:
        
jobs: 
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: src/
          dest: deployable-extension.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/deployable-extension.zip
          
