name: Generate zip file

on:
  workflow_dispatch:
        
jobs: 
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: deployable-extension
          path: /src/
          
          
